// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetTitle(arg1) {
  return window['go']['main']['App']['SetTitle'](arg1);
}

export function Title() {
  return window['go']['main']['App']['Title']();
}
