// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {novels} from '../models';

export function DebugLog(arg1:string,arg2:boolean):Promise<void>;

export function Reset():Promise<void>;

export function Save(arg1:string):Promise<void>;

export function SetTitle(arg1:string):Promise<novels.Novel>;

export function Title():Promise<string>;
