// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Reset():Promise<void>;

export function Save(arg1:string):Promise<void>;

export function SelectDirectory():Promise<void>;

export function SetTitle(arg1:string):Promise<main.Novel>;

export function Title():Promise<string>;
